<?php
$html = file_get_contents("html.html");
/*echo $_SERVER["PATH_INFO"]."\n";*/
/*echo $_SERVER["SCRIPT_URL"]."\n";
echo $_SERVER["SCRIPT_URI"]."\n";
echo $_SERVER["HTTPS"]."\n";
echo $_SERVER["SSL_TLS_SNI"]."\n";*/
/*$http_host = $_SERVER["HTTP_HOST"];
$HTTP_CONNECTION= $_SERVER["HTTP_CONNECTION"];
$HTTP_CACHE_CONTROL = $_SERVER["HTTP_CACHE_CONTROL"];
$HTTP_UPGRADE_INSECURE_REQUESTS = $_SERVER["HTTP_UPGRADE_INSECURE_REQUESTS"];
$HTTP_USER_AGENT= $_SERVER["HTTP_USER_AGENT"];
$HTTP_ACCEPT=$_SERVER["HTTP_ACCEPT"];
if(isset($_SERVER['HTTP_REFERER'])) {$HTTP_REFERER = $_SERVER['HTTP_REFERER'];}
$HTTP_ACCEPT_ENCODING=$_SERVER["HTTP_ACCEPT_ENCODING"];
$HTTP_ACCEPT_LANGUAGE = $_SERVER["HTTP_ACCEPT_LANGUAGE"];
$HTTP_ACCEPT_LANGUAGE = $_SERVER["HTTP_ACCEPT_LANGUAGE"];
/*echo $_SERVER["HTTP_COOKIE"]."\n";*/
//  $SERVER_SIGNATURE = $_SERVER["SERVER_SIGNATURE"];*/
/*
$SERVER_SOFTWARE = $_SERVER["SERVER_SOFTWARE"];
$SERVER_NAME = $_SERVER["SERVER_NAME"];
$SERVER_ADDR = $_SERVER["SERVER_ADDR"];
$SERVER_PORT = $_SERVER["SERVER_PORT"];
$REMOTE_ADDR = $_SERVER["REMOTE_ADDR"];
$DOCUMENT_ROOT = $_SERVER["DOCUMENT_ROOT"];
$REQUEST_SCHEME = $_SERVER["REQUEST_SCHEME"];
$CONTEXT_PREFIX = $_SERVER["CONTEXT_PREFIX"];
$CONTEXT_DOCUMENT_ROOT = $_SERVER["CONTEXT_DOCUMENT_ROOT"];
$SERVER_ADMIN = $_SERVER["SERVER_ADMIN"];
$SCRIPT_FILENAME = $_SERVER["SCRIPT_FILENAME"];
$REMOTE_PORT = $_SERVER["REMOTE_PORT"];
$GATEWAY_INTERFACE = $_SERVER["GATEWAY_INTERFACE"];
$SERVER_PROTOCOL = $_SERVER["SERVER_PROTOCOL"];
$REQUEST_METHOD = $_SERVER["REQUEST_METHOD"];
$QUERY_STRING =$_SERVER["QUERY_STRING"];
$REQUEST_URI = $_SERVER["REQUEST_URI"];
$SCRIPT_NAME = $_SERVER["SCRIPT_NAME"];
$PHP_SELF = $_SERVER["PHP_SELF"];
$REQUEST_TIME_FLOAT = $_SERVER["REQUEST_TIME_FLOAT"];
$REQUEST_TIME = $_SERVER["REQUEST_TIME"];
*/
$parts = explode('---', $html);

 foreach ($_SERVER as $key => $value) {
    $parts[1] .= "<tr><td>".$key.": </td><td>".$value."</td></tr>";
}
$parts = implode($parts);
print_r($parts);
